version: 2.1
orbs:
  architect: giantswarm/architect@5.12.1

workflows:
  package-and-push-chart-on-tag:
    jobs:
    - architect/push-to-app-catalog:
        context: architect
        name: package and push azure-storageclasses chart
        app_catalog: default-catalog
        app_catalog_test: default-test-catalog
        chart: azure-storageclasses
          # Trigger job on git tag.
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore:
            - main
            - master
